### PR TITLE
Match sub_08068578

### PR DESCRIPTION
**Pull request by TraceEntertains**
Somehow match sub_08068578 by doing what the incorrect asm does but in c?

### CODE REVIEW

**Comment by TraceEntertains** [comment]
Now that I think about it, it makes sense, as the compiler was flipping r1 and r0, so flipping them in code double flipped the registers and ended up making it not flipped at all.

**Comment by notyourav** [comment]
src/npc/zeldaFollower.c: In function `sub_08068578':
src/npc/zeldaFollower.c:41: `ZeldaFollowerItem' undeclared (first use in this function)
src/npc/zeldaFollower.c:41: (Each undeclared identifier is reported only once
src/npc/zeldaFollower.c:41: for each function it appears in.)
src/npc/zeldaFollower.c:41: `item' undeclared (first use in this function)
src/npc/zeldaFollower.c:42: syntax error before `index'
src/npc/zeldaFollower.c:72: `r1' undeclared (first use in this function)
src/npc/zeldaFollower.c:74: `r3' undeclared (first use in this function)
src/npc/zeldaFollower.c:75: `r0' undeclared (first use in this function)
src/npc/zeldaFollower.c:76: `r5' undeclared (first use in this function)
src/npc/zeldaFollower.c:81: `r2' undeclared (first use in this function)
src/npc/zeldaFollower.c:95: `r6' undeclared (first use in this function)
src/npc/zeldaFollower.c:127: `r10' undeclared (first use in this function)
src/npc/zeldaFollower.c:136: `r8' undeclared (first use in this function)
src/npc/zeldaFollower.c:147: `y' undeclared (first use in this function)
src/npc/zeldaFollower.c:148: `x' undeclared (first use in this function)
src/npc/zeldaFollower.c:152: invalid lvalue in assignment
src/npc/zeldaFollower.c:152: wrong type argument to decrement

**Comment by TraceEntertains** [comment]
It said it was working on nonmatch.netlify.app
I don't know why it is throwing 15 compiler errors

**Comment by hatal175** [comment]
Not to worry, added the missing struct in new pull request
https://github.com/zeldaret/tmc/pull/594

**Pull request closed without merging**
