### PR TITLE
New Makefile

### PR DESCRIPTION
**Pull request by Henny022p**
Makefile mostly rewritten
Should work mostly identical, except for a few things that were never used (I think)

The most impactful difference is probably that now we don't depend on devkitPro anymore.
It compiler can still be used as before, but a standalone installation of `arm-none-eabi-gcc` works too.

The main functional difference is that this splits things up a bit more to keep things organized.
There is the CMake file that builds the tools.
There is one Makefile that handles everything that is cross-compiled for GBA (+ a toolchain file, to keep things neat)
And one top level Makefile that ties those together.
In normal use only the top level Makefile should be used directly.

This is used as follows (pointing out differences to the old Makefile):
- there are 3 variables that configure the build, `GAME_VERSION` (default USA), `CUSTOM` (default ``, off, set to anything nonempty to enable) and `COMPARE` (sha1 check, defaults to `1`, on for normal builds and `0`, off for custom builds)
- default target is USA rom with SHA1 check (as before)
- utility targets `usa`, `jp`, `eu`, `demo_jp`, `demo_usa` for setting `GAME_VERSION`, as before
- `custom` target for `USA` `CUSTOM` rom (as before)
- `extract_assets`. renamed from `extractassets` for readability, extracts assets from baserom and converts them to a usable format. does not require a manual build before anymore
- `tools` to compile you custom tools. this was `setup` before. since all `setup` does is building tools, this seemed the more fitting name. runs automatically if required before builds
- no more `compare` target. this is no longer needed and was already only provided for compatibility. since we break that already, removed.
- target `all` now builds all 5 versions
- I did not add the `NODEP` option anymore, always doing dependency scanning. It's kinda important and I see no real benefit to disabling it, builds are fast enough as is.
- probably more stuff that I forgot

TODOs:
- testing, especially by other people and on other systems too
- replace `asset_processor build` command with appropriate make rules. this will greately improve custom builds. not necessarily in the scope of this PR
- figure out a nicer way to handle the generated enum asm include files (nice to have, would not block this PR on that)
- probably something else I'm forgetting (I'll update if I remember)

In addition to the nicer files I did also notice a more than 2x speedup during build

### CODE REVIEW

**Comment by notyourav** [comment]
Lgtm, I'll try to test though

**Comment by hatal175** [comment]
You removed the setup target from the makefile so the jenkins build fails.

**Comment by Henny022p** [comment]
I forgot to push that fix

**Comment by Henny022p** [comment]
one important point I forgot:
- I did not add the `NODEP` option anymore, always doing dependency scanning. It's kinda important and I see no real benefit to disabling it, builds are fast enough as is.

I definitely wanna hear a few opinions on this before merging.
Did anyone ever even use it?

**Comment by Henny022p** [comment]
Marking this as ready now.
The other changes too the makefile I wanted to do require a lot of testing so those will be a new PR to not block these changes mich longer

**Pull request merged**
